#!/bin/bash -e

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 PROFILE [CONFIG_DIR]"
    exit -1
fi

# Switch script's directory
cd `dirname $0`

PROFILE=$1
CONFIG_DIR=~/.config/
if [ $# -eq 2 ]; then CONFIG_DIR=$2; fi

# Create symbolic links targeting the configuration directories.
ln -is "`pwd`/${PROFILE}/dotconfig/awesome/" ${CONFIG_DIR}

